import { NextResponse } from 'next/server';
import { withAuth } from '@/server/auth/withAuth';

export const GET = withAuth(async () => {
  const leaderboard = [
    {
      rank: 1,
      userId: 'user_001',
      name: 'Sarah Mitchell',
      profilePicture: null,
      collectionsAmount: 125000,
      invoicesProcessed: 342,
      collectionRate: 94.5,
      points: 4850,
      trend: 'up' as const,
      previousRank: 2,
    },
    {
      rank: 2,
      userId: 'user_002',
      name: 'James Rodriguez',
      profilePicture: null,
      collectionsAmount: 98000,
      invoicesProcessed: 289,
      collectionRate: 91.2,
      points: 4200,
      trend: 'up' as const,
      previousRank: 4,
    },
    {
      rank: 3,
      userId: 'user_003',
      name: 'Emily Chen',
      profilePicture: null,
      collectionsAmount: 87500,
      invoicesProcessed: 267,
      collectionRate: 88.7,
      points: 3850,
      trend: 'down' as const,
      previousRank: 1,
    },
    {
      rank: 4,
      userId: 'user_004',
      name: 'Michael Thompson',
      profilePicture: null,
      collectionsAmount: 76200,
      invoicesProcessed: 234,
      collectionRate: 86.3,
      points: 3400,
      trend: 'same' as const,
      previousRank: 4,
    },
    {
      rank: 5,
      userId: 'user_005',
      name: 'Lisa Patel',
      profilePicture: null,
      collectionsAmount: 65400,
      invoicesProcessed: 198,
      collectionRate: 84.1,
      points: 2950,
      trend: 'up' as const,
      previousRank: 7,
    },
    {
      rank: 6,
      userId: 'user_006',
      name: 'David Kim',
      profilePicture: null,
      collectionsAmount: 54300,
      invoicesProcessed: 176,
      collectionRate: 82.5,
      points: 2600,
      trend: 'down' as const,
      previousRank: 5,
    },
    {
      rank: 7,
      userId: 'user_007',
      name: 'Amanda Foster',
      profilePicture: null,
      collectionsAmount: 42100,
      invoicesProcessed: 145,
      collectionRate: 79.8,
      points: 2100,
      trend: 'up' as const,
      previousRank: 9,
    },
    {
      rank: 8,
      userId: 'user_008',
      name: 'Robert Chang',
      profilePicture: null,
      collectionsAmount: 38500,
      invoicesProcessed: 123,
      collectionRate: 77.2,
      points: 1850,
      trend: 'same' as const,
      previousRank: 8,
    },
  ];

  return NextResponse.json({ leaderboard });
});
